### ISSUE TITLE
When will the code be released?

### ISSUE THREAD

**Issue by TianHongZXY** [yanzhangnlp/BSL#2]
By the way, i'm confused why you use batch normalization rather than layer normalization in the MLP module, which is unusual in NLP. Can you give some explanation or insight? Thanks

**Comment by yanzhangnlp** [comment]
Hi I have released the code. Please feel free to contact me if any questions.  I follow [BYOL](https://arxiv.org/abs/2006.07733) to use the batch norm.  Removing it will not result in much performance degradation (even no degradation).
